In [1]:
import pandas as pd

df = pd.read_excel('NB_vietnam_shopping_behavior.xlsx')

In [2]:
df.head()

,Customer_ID,Age,Gender,City,Category,Item_Purchased,Color,Size,Quantity,Unit_Price_VND,Discount_Applied,Total_Purchase_VND,Payment_Method,Purchase_Channel,Shipping_Type,Season,Purchase_Frequency,Subscription_Member,Promo_Code_Used,Review_Rating
0,1,31,Female,Ho Chi Minh,Running Shoes,FuelCell SuperComp Elite,Pink,37,1,3150000,No,3150000,Cash,In-Store,In-Store Pickup,Summer,Fortnightly,No,No,5.0
1,2,27,Male,Ho Chi Minh,Apparel - Top,Essentials Hoodie,Green,XXL,1,800000,Yes,680000,Cash,Online - Website,Standard,Summer,Fortnightly,No,Yes,2.0
2,3,32,Female,Ha Noi,Lifestyle Sneakers,9060,White,NaN,1,2000000,Yes,2000000,ZaloPay,TikTok Shop,Standard,Winter,Weekly,No,Yes,4.0
3,4,38,Male,Ha Noi,Training Shoes,Minimus TR,Navy,44,1,2550000,No,2550000,Credit Card,Lazada,Standard,Autumn,Weekly,Yes,No,5.0
4,5,26,Female,Ha Noi,Running Shoes,880v13,Beige,42,1,3400000,Yes,3060000,MoMo,In-Store,In-Store Pickup,Autumn,Annually,No,No,3.0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 20 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Customer_ID          3000 non-null   int64
 1   Age                  3000 non-null   int64
 2   Gender               3000 non-null   object
 3   City                 3000 non-null   object
 4   Category             3000 non-null   object
 5   Item_Purchased       3000 non-null   object
 6   Color                3000 non-null   object
 7   Size                 1829 non-null   object
 8   Quantity             3000 non-null   int64
 9   Unit_Price_VND       3000 non-null   int64
 10  Discount_Applied     3000 non-null   object
 11  Total_Purchase_VND   3000 non-null   int64
 12  Payment_Method       3000 non-null   object
 13  Purchase_Channel     3000 non-null   object
 14  Shipping_Type        3000 non-null   object
 15  Season               3000 non-null   object
 16  Purchase_Frequency   3000 non-null   object
 17  Subscription_Member  3000 non-null   object
 18  Promo_Code_Used      3000 non-null   object
 19  Review_Rating        2970 non-null   float64
dtypes: float64(1), int64(5), object(14)
memory usage: 468.9+ KB

In [4]:
df.describe(include='all')

,Customer_ID,Age,Gender,City,Category,Item_Purchased,Color,Size,Quantity,Unit_Price_VND,Discount_Applied,Total_Purchase_VND,Payment_Method,Purchase_Channel,Shipping_Type,Season,Purchase_Frequency,Subscription_Member,Promo_Code_Used,Review_Rating
count,3000.000000,3000.000000,3000,3000,3000,3000.0,3000,1829.0,3000.000000,3.000000e+03,3000,3.000000e+03,3000,3000,3000,3000,3000,3000,3000,2970.000000
unique,NaN,NaN,2,3,6,30.0,10,16.0,NaN,NaN,2,NaN,7,6,4,4,7,2,2,NaN
top,NaN,NaN,Male,Ho Chi Minh,Lifestyle Sneakers,9060.0,Blue,45.0,NaN,NaN,Yes,NaN,MoMo,In-Store,Standard,Summer,Every 3 Months,No,No,NaN
freq,NaN,NaN,1551,1334,938,155.0,325,131.0,NaN,NaN,1614,NaN,689,885,1040,1032,455,2105,2255,NaN
mean,1500.500000,27.845667,NaN,NaN,NaN,NaN,NaN,NaN,1.129667,2.638583e+06,NaN,2.585395e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.983165
std,866.169729,6.646847,NaN,NaN,NaN,NaN,NaN,NaN,0.416627,1.498034e+06,NaN,1.366749e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.009079
min,1.000000,16.000000,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,1.000000e+05,NaN,8.000000e+04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000
25%,750.750000,23.000000,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,9.875000e+05,NaN,1.360000e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.000000
50%,1500.500000,28.000000,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,2.900000e+06,NaN,2.750000e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.000000
75%,2250.250000,32.000000,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,3.750000e+06,NaN,3.556250e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.000000
max,3000.000000,55.000000,NaN,NaN,NaN,NaN,NaN,NaN,3.000000,5.500000e+06,NaN,5.500000e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.000000

In [5]:
df.isnull().sum()

Customer_ID               0
Age                       0
Gender                    0
City                      0
Category                  0
Item_Purchased            0
Color                     0
Size                   1171
Quantity                  0
Unit_Price_VND            0
Discount_Applied          0
Total_Purchase_VND        0
Payment_Method            0
Purchase_Channel          0
Shipping_Type             0
Season                    0
Purchase_Frequency        0
Subscription_Member       0
Promo_Code_Used           0
Review_Rating            30
dtype: int64

In [6]:
df['Review_Rating'] = df.groupby('Category')['Review_Rating'].transform(lambda x: x.fillna(x.median()))

In [7]:
df.isnull().sum()

Customer_ID               0
Age                       0
Gender                    0
City                      0
Category                  0
Item_Purchased            0
Color                     0
Size                   1171
Quantity                  0
Unit_Price_VND            0
Discount_Applied          0
Total_Purchase_VND        0
Payment_Method            0
Purchase_Channel          0
Shipping_Type             0
Season                    0
Purchase_Frequency        0
Subscription_Member       0
Promo_Code_Used           0
Review_Rating             0
dtype: int64

In [8]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ', '_')

In [9]:
df.columns

Index(['customer_id', 'age', 'gender', 'city', 'category', 'item_purchased',
       'color', 'size', 'quantity', 'unit_price_vnd', 'discount_applied',
       'total_purchase_vnd', 'payment_method', 'purchase_channel',
       'shipping_type', 'season', 'purchase_frequency', 'subscription_member',
       'promo_code_used', 'review_rating'],
      dtype='object')

In [10]:
#create a column age_group
labels = ['Teen', 'Young Adult', 'Adult']
df['age_group'] = pd.qcut(df['age'], q = 3, labels=labels)

In [11]:
df[['age', 'age_group']].head(10)

   age    age_group
0   31  Young Adult
1   27  Young Adult
2   32        Adult
3   38        Adult
4   26  Young Adult
5   26  Young Adult
6   39        Adult
7   33        Adult
8   24         Teen
9   31  Young Adult

In [12]:
print(df['age_group'].value_counts())
print(df.groupby('age_group')['age'].agg(['min', 'max']))

age_group
Teen           1120
Young Adult    1017
Adult           863
Name: count, dtype: int64
             min  max
age_group
Teen          16   25
Young Adult   26   31
Adult         32   55

/var/folders/f7/94fw54615592jvyr25yjfj_h0000gn/T/ipykernel_82160/1935641730.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  print(df.groupby('age_group')['age'].agg(['min', 'max']))

In [13]:
# create column purchase_frequency_days
# convert text to numeric for easier compare later 

frequency_mapping = {
    'Fortnightly': 14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Bi-Weekly': 14,
    'Annually': 365,
    'Every 3 Months': 90,
}

df['purchase_frequency_days'] = df['purchase_frequency'].map(frequency_mapping)

In [14]:
df[['purchase_frequency_days', 'purchase_frequency']].head(10)

   purchase_frequency_days purchase_frequency
0                       14        Fortnightly
1                       14        Fortnightly
2                        7             Weekly
3                        7             Weekly
4                      365           Annually
5                        7             Weekly
6                       90          Quarterly
7                        7             Weekly
8                      365           Annually
9                       90          Quarterly

In [15]:
df[['discount_applied', 'promo_code_used']].head(10)

  discount_applied promo_code_used
0               No              No
1              Yes             Yes
2              Yes             Yes
3               No              No
4              Yes              No
5               No              No
6               No              No
7              Yes              No
8               No              No
9              Yes             Yes

In [16]:
(df['discount_applied'] == df['promo_code_used']).all()

np.False_

In [17]:
#df = df.drop('promoo_code_used', axis=1)
#remove if both columns are the same, if not, we can keep both for later analysis

In [18]:
pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in /opt/miniconda3/lib/python3.13/site-packages (2.9.12)
Requirement already satisfied: sqlalchemy in /opt/miniconda3/lib/python3.13/site-packages (2.0.50)
Requirement already satisfied: typing-extensions>=4.6.0 in /opt/miniconda3/lib/python3.13/site-packages (from sqlalchemy) (4.12.2)

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [19]:
from sqlalchemy import create_engine

#Step 1: Connect to PostgreSQL database
username = "postgres"
password = "Anhthu1102"
host = "localhost"
port = "5432"
database = "NB_vietnam_customer_behavior"

engine = create_engine(f'postgresql://{username}:{password}@{host}:{port}/{database}')

#Step 2: Load the cleaned DataFrame into the PostgreSQL database
table_name = "customer"     #choose any table name
df.to_sql(table_name, engine, if_exists='replace', index=False)

print(f"Data successfully loaded into the '{table_name}' table in the PostgreSQL database.")

Data successfully loaded into the 'customer' table in the PostgreSQL database.